#!/bin/bash 
# Set your GitHub username and email 
# Assigning repository name
# Get directory name as repository name by default
# Modify it as you like
repo_name=$1
dir_name=`basename $(pwd)`
if [ "$repo_name" = "" ]; then
  repo_name=$dir_name
fi
# Enther github account info.
export GITHUB_USERNAME="username" 
export GITHUB_EMAIL="email" 
git config --global user.name "${GITHUB_USERNAME}" 
git config --global user.email "${GITHUB_EMAIL}" 
git config --global credential.helper cache 
git config --global credential.helper 'cache --timeout=3600' 
echo "MAKE REPO IN GITHUB"
curl -u "${GITHUB_USERNAME}" https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
echo "[Info] Creating Local Git Repository ...."
git init
git add . 
# Default commit message is 'Init'
# Modify it as you like
git commit -m "Init"
git remote add origin https://github.com/${GITHUB_USERNAME}/$repo_name.git
echo "[Info] Pushing local repository master branch to Github origin/master branch..."
git push -u origin master
